# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data

  adminer:
    container_name: todo-db-adminer
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080